#!/usr/bin/env python3
#
# This file is part of turnkey-version
#
# turnkey-version is open source software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# turnkey-version was initially implemented as ad-hoc version detection
# for a system installed from a TurnKey appliance. Technically this is no
# longer needed as all appliances are marked with their versions. However
# it is still included as a convenience script for gathering the TurnKey
# version.

import sys
import argparse
from pathlib import Path

import sysversion

_ROOTFS = '/'
_TKL_VER = '/etc/turnkey_version'

class TurnkeyVersionError(Exception):
    pass


def main():
    parser = argparse.ArgumentParser(
            description='TurnKey Linux Version information')
    # ensure backwards compatability
    parser.add_argument('rootfs', type=str, nargs="?", default=_ROOTFS,
            help=("Path to root filesystem. If not set; default: '{}'."
                 ).format(_ROOTFS))
    parser.add_argument('-f', '--file', type=str, metavar="PATH/TO/FILE",
            default=_TKL_VER,
            help="Absolute path to file containing turnkey version string. If"
                 " not set; default: '{}'. NOTE: this will be relative to"
                 " rootfs (duplicate slashes ignored).".format(_TKL_VER))
    parser.add_argument('-s', '--string', type=str, metavar="TKL_VER_STR",
            help="Process a string, instead of reading from a file."
                 "('turnkey-' prefix not required). NOTE: If set,"
                 " rootfs &/or -f|--file will be ignored.")
    parser.add_argument('-n', '--name', action="store_true",
            help="Return TurnKey appliance name. E.g. core.")
    parser.add_argument('-t', '--tklversion', action="store_true",
            help="Return TurnKey version number. E.g. 16.0.")
    parser.add_argument('-c', '--codename', action="store_true",
            help="Return relevant Debian codename. E.g. buster.")
    parser.add_argument('-r', '--arch', action="store_true",
            help="Return relevant architechture. E.g. amd64")
    parser.add_argument('-a', '--all', action="store_true",
            help="Return (space separated) name, version, codename & arch."
                 " (Same as -ntcr). NOTE: if multiple individual elements"
                 " returned, this order will be preserved.")
    args = parser.parse_args()
    print(args)
    if args.all and (args.name or args.tklversion or args.codename or args.arch):
        parser.error("-a|--all and -n|--name / -t|--tklversion / -c|--codename"
                     " / -r|--arch are mutually exclusive.")

    if args.string:
        turnkey_version = args.string
    elif args.rootfs or args.file:
        turnkey_version = sysversion.get_turnkey_version(args.rootfs, args.file)
        if not turnkey_version:
            raise TurnkeyVersionError(
                ("can't detect turnkey version - missing or invalid file '{}'."
                ).format(Path(args.rootfs, args.file).resolve()))
    else:
        raise TurnkeyVersionError("This should not be!")

    tkl_appver = []
    tkl_appver_cls = sysversion.AppVer(turnkey_version)
    if args.all:
        args.name = True
        args.tklversion = True
        args.codename = True
        args.arch = True
    if args.name:
        tkl_appver.append(tkl_appver_cls.appname)
    if args.tklversion:
        tkl_appver.append(tkl_appver_cls.tklver)
    if args.codename:
        tkl_appver.append(tkl_appver_cls.codename)
    if args.arch:
        tkl_appver.append(tkl_appver_cls.arch)
    if tkl_appver:
        print(' '.join(tkl_appver))
    else:
        print(turnkey_version)


if __name__ == "__main__":
    main()
